### PR TITLE
Tuxonice 4.8

### PR DESCRIPTION
**Pull request by mschlaeffer**
I made a first attempt to update tuxonice to Linux v4.8.

The code is building, booting and hibernating on Ubuntu:
https://launchpad.net/~tuxonice/+archive/ubuntu/staging

Resume is not working yet (which may be Ubuntu related).

With this pull request I want to give Nigel (and anybody else) the possibility to continue from here.

This pull request contains two commits. The first commit merges Linux v4.8 into Nigel's tuxonice-4.8 branch. The second commit contains the fixes by Tomáš which were merged into tuxonice-head recently.

### CODE REVIEW

**Comment by NigelCunningham** [comment]
Thanks for that, Martin.

I'm finally giving TOI some proper love this weekend - around 3.11 there was an issue that caused me to stop using it myself. I'm trying to address that now.

**Comment by mschlaeffer** [comment]
I have pushed my vagrant scripts to test tuxonice to github. Maybe they are useful to you (especially the tuxonice-cycle.sh one).

With these scripts I see tuxonice stop working for Ubuntu Xenial (Linux v4.4). Unfortunately, vagrant does not work for the Yakkety box yet (Linux v4.8).

**Comment by NigelCunningham** [comment]
Making some progress at last - thanks for your work; the prepare_image.c changes were helpful. I have this booting natively but haven't yet tried to hibernate - still getting the hardware config sorted (I've been running an Ubuntu kernel for a long time). Hopefully not long now though.

**Comment by NigelCunningham** [comment]
Just an update - I have it hibernating and resuming in a VM, but not reliably yet.

**Comment by NigelCunningham** [comment]
I've been using the code natively today, and am up to 8 cycles with no issues so far (large images, too - one was 10GB, compressing by 75%). I'm currently merging and compile-testing older branches and 4.9 and will push updates today or tomorrow.

**Comment by mschlaeffer** [comment]
Thanks a lot Nigel! I'm curious to see your fixes. Please include 4.4 since this is the kernel version of the latest Ubuntu LTS release.

**Comment by NigelCunningham** [comment]
Morning.

4.4 is done. I just need to apply some upstream changes to our code. I had a resume failure this morning (just hung on atomic restore) and have enabled some debugging options that will hopefully provide more info in future.

Nigel

**Pull request closed without merging**
